# Please set AWS credentials
access_key_id:  AKIAIJ4MTZHGQH5LCZ7A
secret_access_key: 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

# please choose one from
# ["ap-northeast-1", "ap-southeast-1", "eu-west-1", "sa-east-1", "us-east-1",
#  "us-west-1", "ap-southeast-2", "us-west-2"]
region: "eu-west-1"

# set a custom AMI to use if you need something other than the defaults
# EBS 14.04 LTS on eu-west, you can find other ami's here e.g.: http://cloud-images.ubuntu.com/locator/ec2/
custom_ami: "ami-81fa71f6"

# array of security groups. e.g. ['sg*** ']
# please make sure to open ports 22(SSH), 5050(Mesos), 8080(Marathon)
security_groups: ['web-app']

# see http://aws.amazon.com/ec2/instance-types/#selecting-instance-types
# for other instance types and its specs.
instance_type: m3.medium

keypair_name: baladorama

ssh_private_key_path: ~/.ssh/CETIC/aws/baladorama.pem
