---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Make Django migrations
  django_manage:
    command: makemigrations
    app_path: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_south_migration
  tags: django.makemigrations

- name: Run Django South migrations
  django_manage:
    command: migrate
    app_path: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_south_migration
  tags: django.migrate

- name: Load django data
  django_manage:
    command: loaddata {{ item }}
    app_path: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  with_items:
    - cities
    - walks
    - poi_types
    - pois
  when: run_django_loaddata
  tags: django.loaddata

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ application_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_collectstatic
  tags: django.collectstatic



